[build]
command = "npm install && npm run build:pages"
publish = "out"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--prefer-offline --no-audit"

[site]
bucket = "out"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin" 