name = "rochesterdeckpros"
main = "./_worker.js"
compatibility_date = "2023-08-01"

# The site will be deployed to rochesterdeckpros.web-66a.workers.dev by default
workers_dev = true

# You can override these in the Cloudflare dashboard
routes = [
  { pattern = "rochesterdeckpros.web-66a.workers.dev", custom_domain = true }
]

# This configures the static assets that will be served by the worker
[site]
bucket = "./out"

# Compatibility
compatibility_flags = ["nodejs_compat"] 