name = "rochesterdeckpros"
main = "./_worker.js"
compatibility_date = "2023-08-01"

# Keep workers.dev domain as a backup
workers_dev = true

# Configure custom domains - rochesterdeckpros.com as main domain
routes = [
  { pattern = "rochesterdeckpros.com/*", zone_name = "rochesterdeckpros.com" },
  { pattern = "www.rochesterdeckpros.com/*", zone_name = "rochesterdeckpros.com" }
]

# This configures the static assets that will be served by the worker
[site]
bucket = "./out"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Compatibility flags
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Properly configure logs
[observability.logs]
enabled = true



