[build]
command = "npm run build"
publish = "out"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = "out"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin" 