[build]
command = "./build.sh"
publishDirectory = ".vercel/output/static"

[build.environment]
NODE_VERSION = "18.18.0"

[site]
bucket = ".vercel/output/static"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin" 