[build]
command = "npm run build:pages"
publishDirectory = ".vercel/output/static"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".vercel/output/static"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin" 